### ISSUE TITLE
[Feature] "PR not ready" state

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-review-plugin#218]
#### Problem to be solved

A Pull Request is always defined as finished and ready for merge/review, That could be a problem if someone is only showing that he is working on a change for a program but does not consider it yet ready for review/merge.

#### Proposed solution

Add a new state that indicates that the PR is not yet ready to be reviewed.

The best place for the creator of the PR to show this would probably be an extra button beside the existing "create Pull-Request"-Button. For the name it would be best to rename the existing button to "create finished PR" and name the new Button "create PR".
That would then also need an extra Button in the PR edit form to mark the PR ready for merge/review. Only if it is ready would the Reviewers be notified that they need to to something. May be there could be a config option to also create a mail on PR creation if that is wished (but with clear meaning that no action is yet needed).

Other possibility would be to use the existing Release feature of a PR so that any other Reviewers are only messaged and propmpted (in the Dashboard) if the Creator has already Released the PR himself. That would than need an extra "Create Releaded PR"-Button in the Create-Form to skip this extra step if it is not needed.

**Comment by Phil-Ah** [comment]
Hey @Shaoranlaos,
We introduced some time ago a new state for PRs to indicate that they are still WIP called “draft Pull Request”. Learn more about this feature in the [docs](https://scm-manager.org/plugins/scm-review-plugin/docs/3.2.x/en/create-pr/). We also explain how to [convert from one state to the other](https://community.cloudogu.com/t/mirroring-worker-persist-even-after-scm-managers-repo-was-deleted/1347).

**Comment by Shaoranlaos** [comment]
Thank you, that seems to do exactly what I needed.
