### ISSUE TITLE
[Error] - Protection Branch does not work (correctly)

### ISSUE THREAD

**Issue by Skyp93** [scm-manager/scm-review-plugin#225]
Hi.
When using branch protection. 
The protection works. But if the user locally creates a branch for himself (in the local repository), and then locally reduces the branch to the master(protected branch). 
Sends the branch to origin, and then sends the master (protected branch) to origin, 
then new changes appear in the protected branch. 
In this case, the protection does not work.
----
Example (by steps): 
1. Create a branch in the local repository (for example, test) and make changes. 
2. Commit changes in the local branch (test). 
3. Merge local changes into a protected branch (without sending to origin, for example test-> master). 
4. Send changes (push) from the local test branch to origin (create a new origin/test branch) 
5. Send changes from the protected branch (Push) (from the master branch) 

**Total: Changes get into Origin/master, while this branch is write-protected without a Pull Request**

Server in Windows. SCM-Manager version 2.46.1. Plugin version: 2.30.1

**Comment by pfeuffer** [comment]
Hi @Skyp93 , thanks for the report, we will take a look at this.

**Comment by pfeuffer** [comment]
Just realized, that we did fix the issue but forgot to report back. The protection should now work with SCM-Manager v2.48.x and the latest review plugin. Thanks once more for the report!
